version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/myapp
    env_file:
      - .env/development/web
      - .env/development/database

  redis:
    image: redis
    volumes:
      - .:/redis-data

  database:
    image: postgres
    env_file:
      - .env/development/web
      - .env/development/database
