version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/myapp
    env_file:
      - .env/development/web
      - .env/development/database

  redis:
    image: redis
    volumes:
      - redis_data:/redis_data

  database:
    image: postgres
    env_file:
      - .env/development/web
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  redis_data:
