version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/myapp
    env_file:
      - .env/development/web
      - .env/development/database

  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/usr/src/myapp
    env_file:
      - .env/development/web
      - .env/development/database
    environment:
      - WEBPACK_DEV_SERVER=0.0.0.0

  redis:
    image: redis
    volumes:
      - redis_data:/redis_data

  database:
    image: postgres
    env_file:
      - .env/development/web
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  redis_data:
